'use strict';
/**
 * The world the security suites run against (roadmap WS-R task 5): Events started in-process
 * (server/index.js start()) on a temp database with a manual clock and a log that is kept, the
 * Network key pair generated by test/helpers.js at load (throwaway, never committed), and:
 *   services   live (publish, read, subscribe), media (the same), network (publish), ops
 *              (events.delivery.admin), and a reader without admin
 *   apps       A (project PA, sandbox), A2 (project PA, production), B (project PB, sandbox)
 *   people     x and y (user tokens), plus realtime tickets for x
 *   subscriptions, each with its signing secret: live's (explicit secret, then rotated: both
 *              secrets sign during the overlap), media's, A's (rotated too), A2's and B's; first-party
 *              deliveries go to a stub on 127.0.0.1, app deliveries through the real guarded poster
 *              with a fake DNS whose public answers the local receiver stands in for
 *   events     public, internal and subject (for x, for y) first-party events, and app events in
 *              each project and environment, each with a distinct marker in its payload
 * `secrets` collects every secret value with a label. Not a test itself (no .test.js).
 */
const nodeHttp = require('http');
const { ids } = require('openvibe-contracts');
const { load } = require('../server/config');
const { start } = require('../server/index');
const apps = require('../server/apps');
const { createGuardedPost, isPublicAddress } = require('../server/egress');
const { privateKey, publicKey, serviceToken, appToken, userToken, realtimeTicket, manualClock, request, envelope, subscriber } = require('./helpers');
const crawler = require('./security-crawl');

const S = (name) => `sentinel-not-a-secret-${name}`;
const ALL = ['events.app.publish', 'events.app.read', 'events.app.subscribe'];

async function buildWorld({ env = {} } = {}) {
    const logged = [];
    const keep = (...a) => { logged.push(a.map((x) => (x && x.stack) || String(x)).join(' ')); if (process.env.DEBUG) console.error(...a); };
    const log = { log: keep, info: keep, warn: keep, error: keep };

    // App endpoints: a fake DNS, and a local receiver standing in for every public address.
    const dnsTable = new Map([['hooks-a.example.com', ['93.184.216.34']], ['hooks-a2.example.com', ['93.184.216.35']], ['hooks-b.example.com', ['93.184.216.36']]]);
    const dnsLookup = (host, opts, cb) => {
        if (typeof opts === 'function') { cb = opts; opts = {}; }
        const list = (dnsTable.get(String(host).toLowerCase()) || []).map((a) => ({ address: a, family: a.includes(':') ? 6 : 4 }));
        if (!list.length) return cb(Object.assign(new Error('not found'), { code: 'ENOTFOUND' }));
        return opts.all ? cb(null, list) : cb(null, list[0].address, list[0].family);
    };
    const appSeen = [];
    const receiver = nodeHttp.createServer((req, res) => {
        const chunks = [];
        req.on('data', (c) => chunks.push(c));
        req.on('end', () => { appSeen.push({ url: req.url, headers: req.headers, rawBody: Buffer.concat(chunks).toString('utf8') }); res.statusCode = 204; res.end(); });
    });
    await new Promise((r) => receiver.listen(0, '127.0.0.1', r));
    const receiverPort = receiver.address().port;
    const appPost = createGuardedPost({
        lookup: (host, opts, cb) => dnsLookup(host, opts, (err, a, f) => {
            if (err) return cb(err);
            const list = (Array.isArray(a) ? a : [{ address: a, family: f }]).map((x) => ({ ...x, address: isPublicAddress(x.address) ? '127.0.0.1' : x.address }));
            return opts.all ? cb(null, list) : cb(null, list[0].address, list[0].family);
        }),
        requestImpl: (options, cb) => nodeHttp.request({ ...options, port: receiverPort }, cb),
        isAllowed: (ip) => ip === '127.0.0.1' || isPublicAddress(ip),
    });

    const clock = manualClock();
    const config = load({ NODE_ENV: 'test', PORT: '0', OV_NETWORK_PUBLIC_KEY: publicKey, EVENTS_WORKER: 'off', ...env });
    const testdb = await require('./db').testDb();   // a database of its own (PGlite, or the containers under test:pg)
    const h = await start({ config, db: testdb.db, clock, log, appPost, dnsLookup });
    const base = `http://127.0.0.1:${h.server.address().port}`;
    const routes = crawler.listRoutes(h.server);

    // ── Principals ───────────────────────────────────────────────────
    const FP = ['events.event.publish', 'events.event.read', 'events.subscription.manage'];
    const PA = `prj_${ids.ulid()}`; const PB = `prj_${ids.ulid()}`;
    const A = ids.newId('app'); const A2 = ids.newId('app'); const B = ids.newId('app');
    const x = ids.newId('user'); const y = ids.newId('user');
    const tok = {
        live: serviceToken('live', FP),
        media: serviceToken('media', FP),
        network: serviceToken('network', ['events.event.publish']),
        ops: serviceToken('ops', ['events.delivery.admin']),
        reader: serviceToken('search', ['events.event.read']),
        appA: appToken({ appId: A, projectId: PA, env: 'sandbox', cap: ALL }),
        appA2: appToken({ appId: A2, projectId: PA, env: 'production', cap: ALL }),
        appB: appToken({ appId: B, projectId: PB, env: 'sandbox', cap: ALL }),
        userX: userToken({ subjectId: x }),
        userY: userToken({ subjectId: y }),
    };
    const call = async (token, method, p, body, headers = {}) => await request(base, method, p, { token, body, headers });
    const must = (r, status, what) => { if (r.status !== status) throw new Error(`${what}: ${r.status} ${r.text.slice(0, 300)}`); return r; };
    const shownOnce = [];
    const once = (what, r) => { shownOnce.push({ what, status: r.status, cache: r.headers.get('cache-control') || '' }); return r; };

    // ── Subscriptions and their secrets ──────────────────────────────
    const fp = await subscriber();
    const secrets = {};
    const subs = {};
    const liveSecret1 = S('live-subscription-secret-1');
    const liveSecret2 = S('live-subscription-secret-2');
    subs.live = once('subscription create (service)', must(await call(tok.live, 'POST', '/api/v1/subscriptions', { topic_pattern: 'live.*', endpoint: fp.url, secret: liveSecret1 }), 201, 'live subscription')).body;
    once('rotate (service)', must(await call(tok.live, 'POST', `/api/v1/subscriptions/${subs.live.id}/rotate-secret`, { secret: liveSecret2, overlap_s: 3600 }), 200, 'live rotate'));
    secrets['live subscription secret (previous, in overlap)'] = liveSecret1;
    secrets['live subscription secret (current)'] = liveSecret2;
    subs.media = must(await call(tok.media, 'POST', '/api/v1/subscriptions', { topic_pattern: 'media.*', endpoint: fp.url.replace('/hook', '/media') }), 201, 'media subscription').body;
    secrets['media subscription secret'] = subs.media.secret;
    const keyA = apps.projectKey(PA); const keyB = apps.projectKey(PB);
    subs.appA = once('subscription create (app)', must(await call(tok.appA, 'POST', '/api/v1/subscriptions', { topic_pattern: `app.${keyA}.*`, endpoint: 'https://hooks-a.example.com/a' }), 201, 'app A subscription')).body;
    secrets['app A subscription secret (previous, in overlap)'] = subs.appA.secret;
    const rotA = once('rotate (app)', must(await call(tok.appA, 'POST', `/api/v1/subscriptions/${subs.appA.id}/rotate-secret`, {}), 200, 'app A rotate')).body;
    secrets['app A subscription secret (current)'] = rotA.secret;
    subs.appA2 = must(await call(tok.appA2, 'POST', '/api/v1/subscriptions', { topic_pattern: `app.${keyA}.*`, endpoint: 'https://hooks-a2.example.com/a2' }), 201, 'app A2 subscription').body;
    secrets['app A2 subscription secret'] = subs.appA2.secret;
    subs.appB = must(await call(tok.appB, 'POST', '/api/v1/subscriptions', { topic_pattern: `app.${keyB}.*`, endpoint: 'https://hooks-b.example.com/b' }), 201, 'app B subscription').body;
    secrets['app B subscription secret'] = subs.appB.secret;
    for (const s of Object.values(subs)) delete s.secret;

    // ── Events, one marker each ──────────────────────────────────────
    const ev = {};
    const pub = async (name, token, body) => { ev[name] = must(await call(token, 'POST', '/api/v1/events', body), 201, `publish ${name}`).body.event_id; };
    await pub('public', tok.live, envelope('live', { visibility: 'public', payload: { title: 'marker-public-live' } }));
    await pub('internal', tok.live, envelope('live', { visibility: 'internal', payload: { title: 'marker-internal-live' } }));
    const note = (to, m) => envelope('network', { event_type: 'network.notification.created', visibility: 'subject', subject: { type: 'user', id: to }, actor: { type: 'service', id: 'network' }, payload: { title: m } });
    await pub('subjectX', tok.network, note(x, 'marker-subject-x'));
    await pub('subjectY', tok.network, note(y, 'marker-subject-y'));
    const appEvent = (appId, projectId, marker) => envelope('x', { source: apps.appSource(appId), event_type: `app.${apps.projectKey(projectId)}.order.created`, actor: { type: 'app', id: appId }, subject: { type: 'order', id: '42' }, visibility: 'internal', payload: { title: marker } });
    await pub('appA', tok.appA, appEvent(A, PA, 'marker-app-a-sandbox'));
    await pub('appA2', tok.appA2, appEvent(A2, PA, 'marker-app-a-production'));
    await pub('appB', tok.appB, appEvent(B, PB, 'marker-app-b-sandbox'));
    await h.worker.drain();

    const markers = {
        public: 'marker-public-live', internal: 'marker-internal-live', subjectX: 'marker-subject-x', subjectY: 'marker-subject-y',
        appA: 'marker-app-a-sandbox', appA2: 'marker-app-a-production', appB: 'marker-app-b-sandbox',
    };
    return {
        h, base, config, clock, routes, logged, secrets, subs, ev, markers, tok, shownOnce, call, fp, appSeen, dnsTable, dnsLookup,
        ids: { PA, PB, A, A2, B, x, y, keyA, keyB }, privateKey, realtimeTicket,
        stop: async () => { await fp.close(); await new Promise((r) => receiver.close(r)); await h.close(); await testdb.close(); },
    };
}

module.exports = { buildWorld, S, ALL };
