'use strict';
// Internal-secret leak (roadmap WS-R task 5). Events holds one kind of secret: each subscription's
// signing secret (service and app subscriptions; after a rotation the previous one keeps signing
// during the overlap). It reads no secret from its environment (asserted below: a new secret-looking
// variable fails this test until it gets a sentinel here); the Network key it verifies with is public,
// and the matching private key (generated by test/helpers.js) must never appear either.
// With the seeded world of test/security-world.js, every GET route Express knows after boot (walked
// from the router stack, so a new route is crawled without anyone listing it) is requested with
// seeded and nonsense ids and several query strings, the realtime stream read for a moment, as
// anonymous, two users (Bearer and cookie), three services (one an operator), a reader and three
// developer apps; then every write route gets malformed JSON from everyone and an empty body from
// anonymous and an app, and every route wrong tokens (forged, alg none, expired, wrong audience).
// No body or header may carry a subscription secret (as is, URL-encoded or base64), another caller's
// token or any part of the private key; the shown-once answers (create, rotate) must be no-store; the
// deliveries sent, the log, and every table but subscriptions must not carry a secret either.
//   node test/security-secrets.test.js
const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { suite, serviceToken, appToken, userToken, ISSUER } = require('./helpers');
const { buildWorld } = require('./security-world');
const crawler = require('./security-crawl');

const t = suite('security-secrets');
let w;
const needles = {};
// Secrets Events does read from its environment, each planted in the world below as a sentinel the crawl looks for.
const PLANTED = { OV_OAUTH_CLIENT_SECRET: `ovsecret-events-client-${crypto.randomBytes(12).toString('hex')}` };

t('Events reads no secret from its environment but the planted ones', async () => {
    const names = new Set();
    const walk = (d) => {
        for (const f of fs.readdirSync(d)) {
            const p = path.join(d, f);
            if (fs.statSync(p).isDirectory()) walk(p);
            else if (p.endsWith('.js')) for (const m of fs.readFileSync(p, 'utf8').matchAll(/\b(?:process\.)?env\.([A-Z][A-Z0-9_]+)|env\[['"]([A-Z][A-Z0-9_]+)['"]\]/g)) names.add(m[1] || m[2]);
        }
    };
    walk(path.join(__dirname, '..', 'server'));
    assert.ok(names.has('DATABASE_URL') && names.has('OV_NETWORK_PUBLIC_KEY'), 'the scan sees the config');
    const secretish = [...names].filter((n) => /SECRET|PASSWORD|TOKEN|PRIVATE|CREDENTIAL|_KEY$/.test(n) && n !== 'OV_NETWORK_PUBLIC_KEY' && !PLANTED[n]);
    assert.deepStrictEqual(secretish, [], 'a new secret-looking variable: give it a sentinel in this test (PLANTED)');
});

t('world', async () => {
    // The Billing client is built (URL and secret set; the loop stays off), so its token client holds the secret.
    w = await buildWorld({ env: { ...PLANTED, OV_BILLING_INTERNAL_URL: 'http://127.0.0.1:9' } });
    assert.strictEqual(w.h.billing.sending, true);
    Object.assign(needles, w.secrets);
    Object.entries(PLANTED).forEach(([name, value]) => { needles[`${name} (planted)`] = value; });
    // The Network private key (Events only ever has the public half).
    const pem = (k) => k.split('\n').filter((l) => l && !l.startsWith('-----'));
    const pub = pem(crypto.createPublicKey(w.privateKey).export({ type: 'spki', format: 'pem' })).join('');
    pem(w.privateKey).forEach((l, i) => { if (!pub.includes(l)) needles[`network private key PEM line ${i}`] = l; });
    const jwk = crypto.createPrivateKey(w.privateKey).export({ format: 'jwk' });
    for (const f of ['d', 'p', 'q', 'dp', 'dq', 'qi']) needles[`network private key JWK ${f}`] = jwk[f];
    assert.strictEqual(Object.keys(w.secrets).length, 7);
});

t('shown once: creation and rotation answer with the secret, never cacheable', async () => {
    assert.strictEqual(w.shownOnce.length, 4);
    for (const s of w.shownOnce) assert.match(s.cache, /no-store/, `${s.what}: Cache-Control no-store`);
});

t('crawl: no GET, refusal or error carries a secret, a token or the key', async () => {
    const { subs, ev, ids } = w;
    const people = {
        anonymous: {},
        userBearer: { authorization: `Bearer ${w.tok.userX}` },
        userCookie: { cookie: `ov_token=${w.tok.userY}` },
        live: { authorization: `Bearer ${w.tok.live}` },
        media: { authorization: `Bearer ${w.tok.media}` },
        ops: { authorization: `Bearer ${w.tok.ops}` },
        reader: { authorization: `Bearer ${w.tok.reader}` },
        appA: { authorization: `Bearer ${w.tok.appA}` },
        appA2: { authorization: `Bearer ${w.tok.appA2}` },
        appB: { authorization: `Bearer ${w.tok.appB}` },
    };
    const tokenOf = (h) => String(h.authorization || h.cookie || '').replace(/^Bearer |^ov_token=/, '');
    const needlesFor = (who) => {
        const n = { ...needles };
        for (const [other, h] of Object.entries(people)) if (other !== who && tokenOf(h)) n[`${other}'s token`] = tokenOf(h);
        return n;
    };
    const values = (name) => ({ id: [subs.live.id, subs.media.id, subs.appA.id, subs.appB.id, ev.public, ev.internal, ev.appA, 'sub_00000000000000000000000000', 'x', '..%2f'] }[name] || ['x']);
    const queries = ['topic=*', 'topic=live.*', `topic=app.${ids.keyA}.*`, `topic=app.${ids.keyB}.*,live.*`, 'status=dead', `subscription_id=${subs.appB.id}`, 'after_seq=0&limit=1000',
        'topics=live.*,network.notification.*&last_event_id=0', 'debug=1&include=secret'];
    const paths = crawler.pathsFor(w.routes, values, { method: 'get', queries, extra: ['/nope', '/api/nope', '/.env', '/data/pglite/PG_VERSION', '/package.json', '/api/v1/subscriptions/../../package.json'] });
    const gets = await crawler.crawl(w.base, paths, people, needlesFor);
    const found = [...gets.found];
    assert.ok(gets.answered === paths.length * Object.keys(people).length, 'every request answered');
    assert.ok((gets.statuses['2xx'] || 0) > 150, `real answers, not only refusals (${JSON.stringify(gets.statuses)})`);
    const st = (who, p) => gets.byPath[`${who} GET ${p}`];
    assert.strictEqual(st('live', '/api/v1/subscriptions'), 200, 'the crawl was signed in');
    assert.strictEqual(st('appA', '/api/v1/subscriptions'), 200);
    assert.strictEqual(st('ops', '/api/v1/deliveries'), 200);
    assert.strictEqual(st('anonymous', '/api/v1/subscriptions'), 401);

    // Error paths: every write route, malformed from everyone, empty from anonymous and an app.
    for (const m of ['post', 'put', 'patch', 'delete']) {
        const list = crawler.pathsFor(w.routes, values, { method: m });
        if (!list.length) continue;
        found.push(...(await crawler.crawl(w.base, list, people, needlesFor, { method: m.toUpperCase(), body: '{"broken": ' })).found);
        found.push(...(await crawler.crawl(w.base, list, { anonymous: {}, appB: people.appB }, needlesFor, { method: m.toUpperCase(), body: '{}' })).found);
    }
    // Wrong tokens of every kind.
    const now = Math.floor(Date.now() / 1000);
    const other = crypto.generateKeyPairSync('rsa', { modulusLength: 2048, privateKeyEncoding: { type: 'pkcs8', format: 'pem' }, publicKeyEncoding: { type: 'spki', format: 'pem' } });
    const b64 = (o) => Buffer.from(JSON.stringify(o)).toString('base64url');
    const wrong = {
        forged: { authorization: `Bearer ${serviceToken('live', ['events.delivery.admin'], { key: other.privateKey })}` },
        algNone: { authorization: `Bearer ${b64({ alg: 'none', typ: 'JWT' })}.${b64({ iss: ISSUER, sub: 'svc:live', actor_type: 'service', aud: ['openvibe.events'], cap: ['events.delivery.admin'], iat: now, exp: now + 300 })}.` },
        expired: { authorization: `Bearer ${serviceToken('live', ['events.delivery.admin'], { exp: now - 60 })}` },
        wrongAudience: { authorization: `Bearer ${serviceToken('live', ['events.delivery.admin'], { aud: 'openvibe.media' })}` },
        appWithAdmin: { authorization: `Bearer ${appToken({ appId: ids.A, projectId: ids.PA, env: 'production', cap: ['events.delivery.admin', 'events.subscription.manage'] })}` },
        userAsService: { authorization: `Bearer ${userToken({ aud: ['openvibe.events'] })}` },
        garbage: { authorization: 'Bearer x.y.z' },
    };
    const wr = await crawler.crawl(w.base, paths.filter((p) => p.startsWith('/api/v1/')), wrong, () => needles);
    found.push(...wr.found);
    const ok2xx = Object.entries(wr.byPath).filter(([, s]) => s < 400).map(([k, s]) => `${k} → ${s}`);
    assert.deepStrictEqual(ok2xx, [], 'wrong tokens open nothing');
    assert.deepStrictEqual(found, [], `secrets in answers:\n${found.join('\n')}`);
});

t('deliveries, the log and the tables carry no secret', async () => {
    const all = { ...needles };
    const sent = [...w.fp.calls.map((c) => ({ text: c.rawBody.toString('utf8'), headers: c.headers })), ...w.appSeen.map((c) => ({ text: c.rawBody, headers: c.headers }))];
    assert.ok(sent.length >= 5, 'deliveries were made');
    for (const s of sent) assert.ok(s.headers['x-openvibe-signature'] || s.headers['x-openvibe-signature-v2'] || Object.keys(s.headers).some((k) => /signature/.test(k)), 'each delivery is signed');
    const inSent = sent.flatMap((s) => crawler.leaks(s, all).map((l) => l.label));
    assert.deepStrictEqual(inSent, [], 'a delivery carries signatures, never the secret');
    const inLog = crawler.leaks({ text: w.logged.join('\n'), headers: {} }, all).map((l) => l.label);
    assert.deepStrictEqual(inLog, [], 'nothing secret was logged');
    const db = w.h.db;
    const tables = (await db.prepare("SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema()").all()).map((r) => r.name).filter((n) => n !== 'subscriptions');
    assert.ok(tables.includes('events') && tables.includes('deliveries'));
    const hits = [];
    for (const tb of tables) for (const l of crawler.leaks({ text: JSON.stringify(await db.prepare(`SELECT * FROM "${tb}"`).all()), headers: {} }, all)) hits.push(`${tb}: ${l.label}`);
    assert.deepStrictEqual(hits, [], 'no secret outside the subscriptions table (events, deliveries, usage outbox)');
});

t('stop', async () => { await w.stop(); });

t.run();
